package pipe.gui.widgets.newwidges.view;

import pipe.gui.ApplicationSettings;
import pipe.gui.widgets.newwidges.bean.DU;
import pipe.gui.widgets.newwidges.bean.GuideModel;
import pipe.gui.widgets.newwidges.bean.SPM;

import javax.swing.*;
import java.util.LinkedList;
import java.util.Queue;

/**
 * Created by hanson on 2017/8/22.
 * 第五步确定接收端RES中分区的数量
 * 下一步为设置每个接收端RES每个分区中的虚链路的个数
 */

public class ModelGuideDialog23 extends JDialog {
    // Variables declaration - do not modify
    private ButtonGroup buttonGroup1;
    //添加备注button
    //private javax.swing.JButton jButtonArray6[] = new javax.swing.JButton[100];

    private JButton jButtonNextStep;
    private JButton jButton3;
    private JButton jButton4;

    private JButton jButton6;

    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel5;

    //第一列的编号
    private JLabel[] jLabelArray1 = new JLabel[100];

    private JLabel jLabel7;
    private JLabel jLabel8;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JSeparator jSeparator1;

    //第二列 ID
    private JTextField[] jTextFieldArray2 = new JTextField[100];

    //第三列 RES中分区的数量
    private JTextField[] jTextFieldArray3 = new JTextField[100];

    // End of variables declaration
    private int returnStatus = RET_CANCEL;

    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;

    private GuideModel nowModel;

    private String[] id = new String[100];

    private Integer[] ParNumber = new Integer[100];
    //private Integer[] Par2VLNumber = new Integer[100];
    //private Integer[] Par3VLNumber = new Integer[100];
    /** Creates new form ModelGuideDialog1 */
    public ModelGuideDialog23(java.awt.Frame parent, boolean modal, GuideModel guideModel) {

        super(parent, modal);
        nowModel = guideModel;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        //获得DU的数量
        int num = nowModel.getNumOfDU();
        setResizable(false);

        for(int i=0; i<num; i++)
        {
            jLabelArray1[i] = new JLabel();
            jTextFieldArray2[i] = new JTextField();
            jTextFieldArray3[i] = new JTextField();
        }
        buttonGroup1 = new ButtonGroup();
        jButton6 = new JButton();
        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jSeparator1 = new JSeparator();
        jButtonNextStep = new JButton();
        jButton3 = new JButton();
        jButton4 = new JButton();
        jPanel2 = new JPanel();


        jLabel5 = new JLabel();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();

        jButton6.setText("添加备注");

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("建模向导");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("第五步");

        jLabel2.setText("<html>请设置每个接收端系统RES中分区的数量<html>");


        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 280, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2))
                                        .addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                                .addContainerGap())
        );

        jButtonNextStep.setText("下一步");
        jButtonNextStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextStepActionPerformed(evt);
            }
        });

        jButton3.setText("取消");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("上一步");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrevStepActionPerformed(evt);
            }
        });

        jLabel5.setText("编号");
        jLabel7.setText("RES_ID");
        jLabel8.setText("RES中分区的数量");

        for(int i=0; i<num; i++)
        {
            jLabelArray1[i].setText("   "+(i+1));
            // 	jTextFieldArray2[i].setActionCommand("jTextFieldArray2_"+(i));
            jTextFieldArray2[i].setText("RES"+(i+1)+"_");
            jTextFieldArray2[i].addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusLost(java.awt.event.FocusEvent evt) {
                    jTextField2_1FocusLost(evt);
                }
            });

            jTextFieldArray3[i].setText("3");

        }

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2Layout.setAutoCreateGaps(true);
        jPanel2Layout.setAutoCreateContainerGaps(true);
        jPanel2.setLayout(jPanel2Layout);
        GroupLayout.ParallelGroup gp1 = jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING);
        gp1.addComponent(jLabel5);
        for(int i=0; i<num; i++)
        {
            gp1.addComponent(jLabelArray1[i]);
        }

        GroupLayout.ParallelGroup gp2 = jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING);
        gp2.addComponent(jLabel7);
        for(int i=0; i<num; i++)
        {
            gp2.addComponent(jTextFieldArray2[i]);
        }

        GroupLayout.ParallelGroup gp3 = jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING);
        gp3.addComponent(jLabel8);
        for(int i=0; i<num; i++)
        {
            gp3.addComponent(jTextFieldArray3[i]);
        }



        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(gp1).addGap(30).addGroup(gp2).addGap(30).addGroup(gp3).addGap(30));//.addGroup(gp4).addGap(30).addGroup(gp5).addGap(30).addGroup(gp55));


        GroupLayout.ParallelGroup gp6 = jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE);
        gp6.addComponent(jLabel5);
        gp6.addComponent(jLabel7);
        gp6.addComponent(jLabel8);
        GroupLayout.SequentialGroup group = jPanel2Layout.createSequentialGroup().addGroup(gp6);

        for(int i=0; i<num; i++)
        {
            //System.out.println("284 num:" + num);
            GroupLayout.ParallelGroup gpTemp = jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE);
            gpTemp.addComponent(jLabelArray1[i]);
            gpTemp.addComponent(jTextFieldArray2[i]);
            gpTemp.addComponent(jTextFieldArray3[i]);
            group.addGroup(gpTemp);
        }

        jPanel2Layout.setVerticalGroup(group);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(318, Short.MAX_VALUE)
                                .addComponent(jButton4)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonNextStep)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)
                                .addGap(8, 8, 8))
                        .addComponent(jSeparator1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton3)
                                        .addComponent(jButtonNextStep)
                                        .addComponent(jButton4))
                                .addContainerGap())
        );
        pack();

    }// </editor-fold>


    private void jTextField2_1FocusLost(java.awt.event.FocusEvent evt) {
        // TODO add your handling code here:

    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        doClose(RET_CANCEL);
    }

    private void jButtonPrevStepActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        //上一步
        int num = nowModel.getNumOfDU();
        for(int i=0; i<num; i++)
        {
            id[i] = jTextFieldArray2[i].getText().trim();
        }
        for(int i=0; i<num; i++)
        {
            if(jTextFieldArray3[i].getText().trim().equals(""))
                ParNumber[i]=0;
            else
                ParNumber[i] = Integer.parseInt(jTextFieldArray3[i].getText());

        }

        Queue<DU> duList = new LinkedList<DU>();
        for(int i=0; i<num; i++)
        {
           DU du = new DU();
           du.setId(this.id[i]);
           //默认为0
           du.setNumOfPar(0);
           duList.add(du);
        }

        this.nowModel.setDuList(duList);
        doClose(RET_CANCEL);
        ModelGuideDialog22 guiDialog1 =  new ModelGuideDialog22(ApplicationSettings.getApplicationView(), true, this.nowModel);
        guiDialog1.pack();
        guiDialog1.setLocationRelativeTo(null);
        guiDialog1.setVisible(true);
    }

    private void jButtonNextStepActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        int num = nowModel.getNumOfDU();

        for(int i=0; i<num; i++)
        {
            id[i] = jTextFieldArray2[i].getText().trim();
            if(id[i].equals(""))
            {
                JOptionPane.showMessageDialog(this, "ID不能为空", "Warning",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
        }

        for(int i=0; i<num; i++)
        {
            if(jTextFieldArray3[i].getText().trim().equals(""))
            {
                JOptionPane.showMessageDialog(this, "参数不能为空", "Warning",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
            ParNumber[i] = Integer.parseInt(jTextFieldArray3[i].getText());


        }
        Queue<DU> duList = new LinkedList<DU>();
        for(int i=0; i<num; i++)
        {
           DU du = new DU();
           du.setId(this.id[i]);
           //默认为0
           du.setNumOfPar(ParNumber[i]);
           duList.add(du);
        }

        this.nowModel.setDuList(duList);

        doClose(RET_OK);
    	ModelGuideDialog32 guiDialog =  new ModelGuideDialog32(ApplicationSettings.getApplicationView(), true, this.nowModel);
        guiDialog.pack();
        guiDialog.setLocationRelativeTo(null);
        guiDialog.setVisible(true);
    }
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModelGuideDialog1 dialog = new ModelGuideDialog1(new JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
}
